Repository TeamGrabit/Grabit_backend, pull requests merged in 2022-07, with the labels that each got.

#41 [Stomp] fix Stomp CORS error
  src/main/java/grabit/grabit_backend/config/security/SecurityConfig.java
  src/main/java/grabit/grabit_backend/config/stomp/StompConfig.java
  src/main/java/grabit/grabit_backend/config/websocket/StompWebSocketConfig.java
  src/main/java/grabit/grabit_backend/config/websocket/WebsocketConfig.java
Labels: :hammer_and_wrench: Fix

#45 [Image] image 반환값 형태 수정.
  src/main/java/grabit/grabit_backend/controller/S3Controller.java
  src/main/java/grabit/grabit_backend/dto/ResponseImageURLDTO.java
Labels: :hammer_and_wrench: Fix

#44 [CommitApproval] Commit 요청 API 작성.
  src/main/java/grabit/grabit_backend/controller/ChallengeController.java
  src/main/java/grabit/grabit_backend/controller/PassApprovalController.java
  src/main/java/grabit/grabit_backend/converter/PassApprovalResultStatusConverter.java
  src/main/java/grabit/grabit_backend/domain/Challenge.java
  src/main/java/grabit/grabit_backend/domain/PassApproval.java
  src/main/java/grabit/grabit_backend/domain/PassApprovalResult.java
  src/main/java/grabit/grabit_backend/dto/CreatePassApprovalDTO.java
  src/main/java/grabit/grabit_backend/dto/ResponsePassApprovalDTO.java
  src/main/java/grabit/grabit_backend/enums/PassApprovalResultStatus.java
  src/main/java/grabit/grabit_backend/exception/NotFoundChallengeException.java
  src/main/java/grabit/grabit_backend/exception/NotFoundPassApprovalException.java
  src/main/java/grabit/grabit_backend/repository/PassApprovalRepository.java
  src/main/java/grabit/grabit_backend/repository/PassApprovalResultRepository.java
  src/main/java/grabit/grabit_backend/service/ChallengeService.java
  src/main/java/grabit/grabit_backend/service/PassApprovalService.java
Labels: :sparkles: Feature

#46 GET 챌린지 api 인증 해제
  src/main/java/grabit/grabit_backend/config/security/SecurityConfig.java
  src/main/java/grabit/grabit_backend/controller/ChallengeController.java
  src/main/java/grabit/grabit_backend/service/ChallengeService.java
Labels: :guitar: Chore
