Repository TeamGrabit/Grabit_backend, pull requests merged in 2022-04, with the labels that each got.

#29 Feat/upate user api
  src/main/java/grabit/grabit_backend/Oauth2/handler/CustomOAuth2UserService.java
  src/main/java/grabit/grabit_backend/controller/UserController.java
  src/main/java/grabit/grabit_backend/domain/OAuthAttributes.java
  src/main/java/grabit/grabit_backend/domain/User.java
  src/main/java/grabit/grabit_backend/dto/ResponseUserDTO.java
  src/main/java/grabit/grabit_backend/dto/UpdateUserDTO.java
  src/main/java/grabit/grabit_backend/dto/UserResDTO.java
  src/main/java/grabit/grabit_backend/exception/ForbiddenException.java
  src/main/java/grabit/grabit_backend/service/UserService.java
Labels: :sparkles: Feature

#28 [Query] @Query를 통해 N+1문제 해결.
  build.gradle
  src/main/java/grabit/grabit_backend/config/querydsl/QueryDslConfig.java
  src/main/java/grabit/grabit_backend/controller/ChallengeController.java
  src/main/java/grabit/grabit_backend/domain/Challenge.java
  src/main/java/grabit/grabit_backend/domain/UserChallenge.java
  src/main/java/grabit/grabit_backend/repository/ChallengeCustomRepository.java
  src/main/java/grabit/grabit_backend/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/grabit/grabit_backend/repository/ChallengeRepository.java
  src/main/java/grabit/grabit_backend/service/ChallengeService.java
  src/main/resources/application.properties
Labels: :hammer_and_wrench: Fix, :guitar: Chore

#31 Fix: 권한 적용 url 설정 변경
  src/main/java/grabit/grabit_backend/config/security/SecurityConfig.java
Labels: :hammer_and_wrench: Fix
